Fix error when ancestry field is integer
- Problem
When the field field ancestry is an integer on database the method
`parse_ancestry_column` raise error because of split is not a method
of integer

- Solution
Return the method `to_s` on the method `parse_ancestry_column` to change
integer to string before do the split

- Error Log

```
NoMethodError:
        undefined method `split' for 13654:Fixnum
      # /home/klaus/.rvm/gems/ruby-2.3.1/gems/ancestry-3.0.7/lib/ancestry/instance_methods.rb:381:in `parse_ancestry_column'
      # /home/klaus/.rvm/gems/ruby-2.3.1/gems/ancestry-3.0.7/lib/ancestry/instance_methods.rb:153:in `ancestor_ids'
```

- Issue: #446